shiro:
  jwt:
    expiration: 30000
    secret: secret
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/shiro-test?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver